import React from 'react';

export default props => (
    <div>
        <h1 className="text-center">Secret Documents</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus est deserunt deleniti accusamus ea ab corporis exercitationem, laborum, fugiat, cumque fugit molestiae. Accusamus, molestias. Veniam itaque assumenda quo asperiores doloremque dolores nobis voluptatum ut modi ab voluptate eius harum iusto, libero cumque repudiandae numquam amet. Error ipsum consequatur aperiam nostrum sit nesciunt dolor, alias doloremque sunt dolore consequuntur saepe unde minima. Numquam eum reprehenderit quae pariatur, architecto possimus optio cum tempore quaerat sed eligendi a suscipit earum impedit ex obcaecati vero molestiae? Illo laboriosam aperiam doloremque quod! Ut nulla nisi maiores soluta, perspiciatis ipsa inventore nobis labore a, laborum, animi vel. Laboriosam saepe veniam accusantium fugit quod officiis, ea perspiciatis quas consequuntur aspernatur omnis, quidem odit officia architecto porro ducimus? Architecto autem quaerat quam vitae recusandae consectetur earum fugiat reprehenderit nulla, pariatur laudantium expedita facilis veniam nobis. Quibusdam rem saepe excepturi delectus rerum modi, quas, expedita earum nam ea dolor neque soluta dicta laborum a ipsum ratione quaerat officia labore laudantium est aut deserunt iste harum. Animi iure eum eaque excepturi reprehenderit esse suscipit aperiam dolor eius, cupiditate nisi tempora repellendus adipisci quaerat consequuntur quis corporis illum non quod corrupti quas quo ducimus laboriosam. Perspiciatis distinctio odio porro dolorem nulla.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio sed rerum illo consequatur nam distinctio rem id unde, excepturi fugit ipsam vel ratione ullam nulla eius adipisci, beatae voluptatem asperiores neque ab pariatur. Voluptatibus rerum deleniti voluptate quis repellendus non, illo, consequuntur ullam provident iusto sit libero nesciunt asperiores quam.
        Eos in ea veniam laboriosam voluptatum id, placeat dolorem labore, tempore fuga quaerat, sit sint? Laboriosam quae veniam ad minima nam architecto suscipit voluptate blanditiis. Numquam asperiores animi labore, repellat, atque veniam, error sunt consequatur placeat alias molestiae. Perspiciatis asperiores omnis soluta corporis eaque, nobis obcaecati? Natus laudantium praesentium eveniet.
        Quae provident aliquam optio repudiandae, quam minus sapiente totam nam adipisci nulla error fugiat dolorum eos ipsam maxime dolorem voluptate animi consequatur commodi, beatae quia ea? Ipsam dicta ea aliquam, dignissimos, libero architecto asperiores officia fugit, autem porro dolorum ratione ut dolorem eaque. Aliquid quis in sint eligendi numquam quibusdam!
        Officia quia magni fuga nesciunt natus libero voluptate blanditiis ad aliquid perspiciatis, neque voluptatem laudantium numquam magnam vitae. Placeat, pariatur ea beatae error repellendus a officiis, magnam repudiandae, tempora saepe minima ab quibusdam neque inventore animi? Adipisci, labore voluptatum ab molestias porro doloribus suscipit repellendus. Ducimus quam magni ipsa ratione?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam, consequatur. Nihil alias neque iusto! Commodi quidem placeat quasi culpa aperiam.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio nostrum nihil debitis nisi sed sint cum perspiciatis nesciunt sequi doloremque!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, sunt magni deleniti dignissimos at est voluptas odit commodi aliquid architecto.</p>
    </div>
)
